### PR TITLE
➕ Add language code support

### PR DESCRIPTION
**Pull request by YazeedAlKhalaf**
This PR allows the use of the `language` query parameter to change the language of results which is so useful!

### CODE REVIEW

**Comment by HermanFassett** [comment]
Thanks it honestly looks good but I can't really look at it closely now, I'll try to check it out later today

**Comment by YazeedAlKhalaf** [comment]
That's great to hear 🚀😍

**Comment by HermanFassett** [comment]
Sorry I wasn't able to check it out yesterday, and can't until later today. Looks like it will need a package.json version bump though

**Comment by YazeedAlKhalaf** [comment]
@HermanFassett It been a while 😂🙈🚀

**Comment by YazeedAlKhalaf** [comment]
hi it has been 9 months 🙈

**Pull request closed without merging**
